<?php
ob_start(); //START OUTPUT BUFFERING
session_start(); //START THE SESSION

//INCLUDEs
include('../system/FDPDF/fpdf.php');
require('../conn.php');
require('../audit_trail.php');

//FOR TIME FORMATTING
date_default_timezone_set('Asia/Manila');
$fileDateFormat = date('mdy');

//GENERATE LOG, BEFORE CREATING A REPORT
function recordLog() {
    logActivity("List of Church Orgs. Report Generated");
}
recordLog();



class PDF extends FPDF {

    //PAGE HEADER FUNCTION
    function Header() {
        //HEADER
        $this->SetFont('Arial', 'B', 12);
        $this->Cell(0, 1, 'CH-MS LIST OF CHURCH ORGANIZATIONS REPORT', 0, 1, 'C');
        $this->SetFont('Arial', '', 10);
        $this->Cell(0, 10, 'AS OF ' . date('Y-m-d H:i:s') . '. GENERATED BY ' . $_SESSION['name'], 0, 1, 'C');

        //HEADER FORMATTING
        $this->SetFillColor(200, 220, 255);
        $this->SetTextColor(0);
        $this->SetDrawColor(0);
        $this->SetLineWidth(0.2);
        
        //TABLE HEADER DATA
        $this->SetFont('Arial', 'B', 12);
        //WIDTH, HEIGHT, TEXT INSIDE, BORDER (boolean), NEXT CELL BELOW, CENTER, FILL COLOR (boolean)
        $this->Cell(30, 10, 'ID', 1, 0, 'C', true);
        $this->Cell(245, 10, 'ORGANIZATION NAME', 1, 1, 'C', true);
    }

    //PAGE FOOTER FUNCTION
    function Footer() {
        $this->SetY(-15);
        $this->SetFont('Arial', 'I', 8);
        $this->Cell(0, 10, 'PAGE '.$this->PageNo().' OF {nb}', 0, 0, 'R');
    }
}



try {
    //CREATE NEW PDF DOCUMENT, LANDSCAPE, A4
    $pdf = new PDF('L', 'mm', 'A4');
    $pdf->AliasNbPages();
    $pdf->AddPage();

    //SET FONT SIZE
    $pdf->SetFont('Arial', '', 10);

    //GET DATA FROM THE DATABASE
    $sql = "SELECT * FROM organizations";
    $result = $conn->query($sql);

    //CHECK IF THERE ARE RESULTS TO DISPLAY IN THE REPORT
    if ($result->num_rows > 0) {
        //OUTPUT FETCHED DATA TO THE PDF
        while ($row = $result->fetch_assoc()) {
            //WIDTH, HEIGHT, CONTENT, BORDER (boolean), POSITION IF NEXT LINE, CENTER
            $pdf->Cell(30, 10, $row['Id'], 1, 0, 'C');
            $pdf->Cell(245, 10, $row['Name'], 1, 1, 'C');
        }

    } else {
        //IF NO RESULTS FOUND, DISPLAY A MESSAGE IN THE REPORT
        $pdf->Cell(0, 10, 'NO RESULTS FOUND', 0, 1);
    }

    //DOWNLOAD THE REPORT ON BROWSER ('D' DOWNLOAD, 'I' INLINE DISPLAY)
    $pdfFilename = 'chms_orgs_list_' . $fileDateFormat . '.pdf';
    ob_clean(); //CLEAN THE OUTPUT BUFFER BEFORE PDF OUTPUT
    $pdf->Output($pdfFilename, 'D');

} catch (Exception $e) {
    //ANY ERRORS, HANDLE IT
    echo 'CAUGHT EXCEPTION: ', $e->getMessage(), "\n";
}

ob_end_flush(); //FLUSH THE OUTPUT BUFFER
?>