<?php
session_start(); // Start the session

include('../system/FDPDF/fpdf.php');
require('../conn.php');
require('../audit_trail.php');

date_default_timezone_set('Asia/Manila');
$fileDateFormat = date('mdy');

class PDF extends FPDF {
    // Page header
    function Header() {
        // Logo or header content can be added here
        $this->SetFont('Arial', 'B', 12);
        $this->Cell(0, 1, 'CH-MS AUDIT TRAIL REPORT', 0, 1, 'C');
        $this->SetFont('Arial', '', 10);
        $this->Cell(0, 10, 'as of ' . date('Y-m-d H:i:s') . ' generated by ' . $_SESSION['name'], 0, 1, 'C');

        // Table header
        $this->SetFillColor(200, 220, 255);
        $this->SetTextColor(0);
        $this->SetDrawColor(0);
        $this->SetLineWidth(0.2);
        
        $this->SetFont('Arial', 'B', 12);
        $this->Cell(40, 10, 'ACTIVITY ID', 1, 0, 'C', true);
        $this->Cell(60, 10, 'CURRENT USER', 1, 0, 'C', true);
        $this->Cell(120, 10, 'ACTIVITY', 1, 0, 'C', true);
        $this->Cell(60, 10, 'TIME', 1, 1, 'C', true);
    }

    // Page footer
    function Footer() {
        $this->SetY(-15);
        $this->SetFont('Arial', 'I', 8);
        $this->Cell(0, 10, 'Page '.$this->PageNo().' of {nb}', 0, 0, 'R');
    }

}

// create new PDF document
$pdf = new PDF('L', 'mm', 'A4');
$pdf->AliasNbPages();
$pdf->AddPage();

// set font
$pdf->SetFont('Arial', '', 10);

// Fetch data from the database
$sql = "SELECT * FROM activity_logs";
$result = $conn->query($sql);

if ($result->num_rows > 0) {
    while ($row = $result->fetch_assoc()) {
        $pdf->Cell(40, 10, $row['id'], 1, 0, 'C');
        $pdf->Cell(60, 10, $row['user'], 1, 0, 'C');
        $pdf->Cell(120, 10, $row['activity_description'], 1, 0, 'C');
        $pdf->Cell(60, 10, $row['created_at'], 1, 1, 'C');
    }
} else {
    $pdf->Cell(0, 10, 'No results found', 0, 1);
}

// Output PDF to the browser or file ('D' for download, 'I' for inline display)
$pdfFilename = 'chms_audit_trail_' . $fileDateFormat . '.pdf';
$pdf->Output($pdfFilename, 'D');
